version: '2'
services:
  centos:
    build:
      context: .
      dockerfile: Dockerfile-centos
    image: hpfeeds:centos
  ubuntu:
    build:
      context: .
      dockerfile: Dockerfile-ubuntu
    image: hpfeeds:ubuntu
