---
  pkgs:
    - gcc
    - git
    - sqlite
    - mongodb

  pip_executable: pip2

  chn_logdir: /var/log/mhn

  hpfeeds_pip_pkgs:
    - cffi
    - pyopenssl
    - pymongo

  hpfeeds_pip_pkgs_editable:
    - git+https://github.com/CommunityHoneyNetwork/pyev.git#subdirectory=pyev-0.9.0
    - git+https://github.com/CommunityHoneyNetwork/evnet.git#egg=evnet-dev

  broker_dir: /opt/hpfeeds/broker
